CREATE DATABASE IF NOT EXISTS `yourvote` DEFAULT CHARACTER SET utf8mb4;
USE `yourvote`;

CREATE TABLE IF NOT EXISTS `user` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(20) NOT NULL,
  `password` VARCHAR(36) NOT NULL,
  `email` VARCHAR(50) NOT NULL,
  `wallet` VARCHAR(50) NOT NULL,
  `created_at`DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `email` (`email`)
) AUTO_INCREMENT=1 DEFAULT CHARSET=utf8;
